### PR TITLE
Fixes undefined error variable in try/catch 

### PR DESCRIPTION
**Pull request by alexzel**
issue https://github.com/AsaAyers/coffeelint-undefined-variables/issues/4

### CODE REVIEW

**Comment by alexzel** [comment]
added `disableCommentsLinting` config option

**Comment by alexzel** [comment]
which comments style is expecting there? why there just `global` instead of using some prefix like `@global`?

**Comment by alexzel** [comment]
actually an approach how vars are describing in comment could be really different and depends of dev conventions used for some project, but that code already expecting to get them in some format, so I think that option for disabling comments linting definitely makes sense, but of course the regex should be fixed too

**Comment by AsaAyers** [comment]
Lets look at how other linters handle this issue.

jshint: `/* global MY_GLOBAL */`
eslint: `/*global var1, var2*/`
jslint: `/*global
ADSAFE, document, REPORT, jslint
*/`

Looking at that the correct way to declare globals with CoffeeLint is and will remain `###global YourGlobalVariable, AnotherVariable ###`.

Turning off the ability to declare that a file needs a global variable is unacceptable.

> I think that option for disabling comments linting definitely makes sense

I will never merge such an option, but one of the great things about allowing 3rd party plugins is that you're welcome to build your own plugin that works exactly the way you want.

**Pull request closed without merging**
